# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181011_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Municipality', verbose_name='Муниципальное образование'),
        ),
    ]
