# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181019_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfo',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Locality', verbose_name='Населенный пункт'),
        ),
    ]
