# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 08:05
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181021_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ('name',), 'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name',), 'verbose_name': 'Муниципальное образование', 'verbose_name_plural': 'Муниципальные образования'},
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='locality',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipality', chained_model_field='municipality', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Locality', verbose_name='Населенный пункт'),
        ),
    ]
