# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-07 19:33
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181024_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dashboard.models.image_folder)),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='OKN_in_ensemble',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='ОКН входит в ансамбль (да/нет)'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='affiliation_U',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Принадлежность к ЮНЭСКО'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='esp_valuable_object',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Особо ценный объект'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_docs_boundaries',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документов о границах территории ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_docs_of_aprroval',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документов об утвержденых зонах охраны'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_passport_OKN',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('На подготовке', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие паспорта ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_rights',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие зарегистрированных прав/обременений'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='has_security_obligation',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('На подготовке', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие охранного обязательства ОКН'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='information_sign',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('На подготовке', 'На подготовке')], max_length=5, null=True, verbose_name='Наличие уcтановленной информационной надписи установленного образца'),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='information_sign_conformity',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие информационной надписи, но не соответствующей требованиям'),
        ),
        migrations.AddField(
            model_name='image',
            name='objectinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ObjectInfo'),
        ),
    ]
